FROM docker.io/library/ubuntu:23.04

# Remove apt configuration optimized for containers
# Remove docker-gzip-indexes to help with "command-not-found"
RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages

# Enable myhostname nss plugin for clean hostname resolution without patching
# hosts (at least for sudo), add it right after 'files' entry. We expect that
# this entry is not present yet. Do this early so that package postinst (which
# adds it too late in the order) skips this step
RUN sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf

# Restore documentation and update everything
RUN sed -Ei '/apt-get (update|upgrade)/s/^/#/' /usr/local/sbin/unminimize && \
  apt-get update -y && apt-get upgrade -y && \
  yes | /usr/local/sbin/unminimize

# Install extra packages
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install \
  # These packages are part of a typical toolbox image
  ubuntu-minimal \
  ubuntu-standard \
  libnss-myhostname \
  curl \
  flatpak-xdg-utils \
  git \
  gnupg2 \
  keyutils \
  tree \
  unzip \
  zip \
  zsh \
  # These packages are the ones distrobox wants to install on first start
  bash \
  bc \
  dialog \
  diffutils \
  findutils \
  less \
  libegl1-mesa \
  libgl1-mesa-glx \
  libvte-2.9*-common \
  libvulkan1 \
  lsof \
  mesa-vulkan-drivers \
  ncurses-base \
  passwd \
  pinentry-curses \
  procps \
  sudo \
  time \
  util-linux \
  wget

# Fix empty bind-mount to clear selinuxfs
RUN mkdir /usr/share/empty

# Add flatpak-spawn to /usr/bin
RUN ln -s /usr/libexec/flatpak-xdg-utils/flatpak-spawn /usr/bin/
