name: build-ubuntu
on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntu/**
  push:
    branches:
      - main
    paths:
      - ubuntu/**
  schedule:
    - cron: "0 0 * * MON"

env:
  IMAGE_NAME: ubuntu
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build_ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntu
