name: build-all-ubuntu-images
on:
  push:
    branches:
      - main
    paths:
      - ubuntu/**
  schedule:
    - cron: "0 0 * * MON"

jobs:
  build_ubuntu:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntu
  build_ubuntubox:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntubox
