name: build-ubuntubox
on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntubox/**
  push:
    branches:
      - main
    paths:
      - ubuntubox/**
  schedule:
    - cron: "0 1 * * MON"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntubox
