name: build-ubuntubox
on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntubox/**
  push:
    branches:
      - main
    paths:
      - ubuntubox/**

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntubox
