name: build-ubuntu
on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntu/**
  schedule:
    - cron: "0 0 * * MON"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntu
