name: build-ubuntubox
on:
  pull_request:
    branches:
      - main
    paths:
      - ubuntubox/**
  push:
    branches:
      - main
    paths:
      - ubuntubox/**
  schedule:
    - cron: "0 0 * * MON"

env:
  IMAGE_NAME: ubuntubox
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      image_name: ubuntubox
